package com.audiolan.app.ui.theme

import androidx.compose.ui.graphics.Color

// Accent preset seeds. Complete Material 3 schemes are derived from these in Theme.kt.
val LavenderSeed: Color = Color(0xFFC5B4F0)
val TealSeed: Color = Color(0xFF80CBC4)
val AmberSeed: Color = Color(0xFFFFCC80)
val RoseSeed: Color = Color(0xFFF48FB1)
val SkySeed: Color = Color(0xFF81D4FA)
val BlueSeed: Color = Color(0xFF90CAF9)
val GreenSeed: Color = Color(0xFFA5D6A7)
val LimeSeed: Color = Color(0xFFDCE775)
val OrangeSeed: Color = Color(0xFFFFAB91)
val VioletSeed: Color = Color(0xFFCE93D8)

internal val M3DarkBackground: Color = Color(0xFF131316)
internal val M3DarkOnBackground: Color = Color(0xFFE6E1E5)
internal val M3DarkSurface: Color = Color(0xFF131316)
internal val M3DarkOnSurface: Color = Color(0xFFE6E1E5)
internal val M3DarkSurfaceVariant: Color = Color(0xFF49454F)
internal val M3DarkOnSurfaceVariant: Color = Color(0xFFCAC4D0)
internal val M3DarkSurfaceDim: Color = Color(0xFF131316)
internal val M3DarkSurfaceBright: Color = Color(0xFF39383C)
internal val M3DarkSurfaceContainerLowest: Color = Color(0xFF0E0E11)
internal val M3DarkSurfaceContainerLow: Color = Color(0xFF1D1B20)
internal val M3DarkSurfaceContainer: Color = Color(0xFF211F26)
internal val M3DarkSurfaceContainerHigh: Color = Color(0xFF2B2930)
internal val M3DarkSurfaceContainerHighest: Color = Color(0xFF36343B)
internal val M3DarkOutline: Color = Color(0xFF938F99)
internal val M3DarkOutlineVariant: Color = Color(0xFF49454F)
internal val M3DarkError: Color = Color(0xFFFFB4AB)
internal val M3DarkOnError: Color = Color(0xFF690005)
internal val M3DarkErrorContainer: Color = Color(0xFF93000A)
internal val M3DarkOnErrorContainer: Color = Color(0xFFFFDAD6)
internal val M3DarkInverseSurface: Color = Color(0xFFE6E1E5)
internal val M3DarkInverseOnSurface: Color = Color(0xFF313033)

internal val M3LightBackground: Color = Color(0xFFFFFBFE)
internal val M3LightOnBackground: Color = Color(0xFF1C1B1F)
internal val M3LightSurface: Color = Color(0xFFFFFBFE)
internal val M3LightOnSurface: Color = Color(0xFF1C1B1F)
internal val M3LightSurfaceVariant: Color = Color(0xFFE7E0EC)
internal val M3LightOnSurfaceVariant: Color = Color(0xFF49454F)
internal val M3LightSurfaceDim: Color = Color(0xFFDED8E1)
internal val M3LightSurfaceBright: Color = Color(0xFFFFFBFE)
internal val M3LightSurfaceContainerLowest: Color = Color(0xFFFFFFFF)
internal val M3LightSurfaceContainerLow: Color = Color(0xFFF7F2FA)
internal val M3LightSurfaceContainer: Color = Color(0xFFF3EDF7)
internal val M3LightSurfaceContainerHigh: Color = Color(0xFFECE6F0)
internal val M3LightSurfaceContainerHighest: Color = Color(0xFFE6E0E9)
internal val M3LightOutline: Color = Color(0xFF79747E)
internal val M3LightOutlineVariant: Color = Color(0xFFCAC4D0)
internal val M3LightError: Color = Color(0xFFBA1A1A)
internal val M3LightOnError: Color = Color(0xFFFFFFFF)
internal val M3LightErrorContainer: Color = Color(0xFFFFDAD6)
internal val M3LightOnErrorContainer: Color = Color(0xFF410002)
internal val M3LightInverseSurface: Color = Color(0xFF313033)
internal val M3LightInverseOnSurface: Color = Color(0xFFF4EFF4)

internal val M3Scrim: Color = Color(0xFF000000)
